package model;
// Generated Aug 29, 2017 11:31:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblCategoria generated by hbm2java
 */
public class TblCategoria  implements java.io.Serializable {


     private int codigoCategoria;
     private String nombre;
     private boolean activo;
     private Set tblProductos = new HashSet(0);

    public TblCategoria() {
    }

	
    public TblCategoria(int codigoCategoria, String nombre, boolean activo) {
        this.codigoCategoria = codigoCategoria;
        this.nombre = nombre;
        this.activo = activo;
    }
    public TblCategoria(int codigoCategoria, String nombre, boolean activo, Set tblProductos) {
       this.codigoCategoria = codigoCategoria;
       this.nombre = nombre;
       this.activo = activo;
       this.tblProductos = tblProductos;
    }
   
    public int getCodigoCategoria() {
        return this.codigoCategoria;
    }
    
    public void setCodigoCategoria(int codigoCategoria) {
        this.codigoCategoria = codigoCategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getTblProductos() {
        return this.tblProductos;
    }
    
    public void setTblProductos(Set tblProductos) {
        this.tblProductos = tblProductos;
    }




}


