package model;
// Generated Aug 29, 2017 11:31:30 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblCompraReferencia generated by hbm2java
 */
public class TblCompraReferencia  implements java.io.Serializable {


     private long codigoCompraR;
     private TblEmpleado tblEmpleado;
     private String documento;
     private Date fecha;
     private BigDecimal total;
     private boolean confirmado;
     private String numeroEnvio;
     private Date fechaConfirmacion;
     private boolean anulado;
     private Set tblCompraDetalles = new HashSet(0);

    public TblCompraReferencia() {
    }

	
    public TblCompraReferencia(long codigoCompraR, TblEmpleado tblEmpleado, String documento, Date fecha, BigDecimal total, boolean confirmado, Date fechaConfirmacion, boolean anulado) {
        this.codigoCompraR = codigoCompraR;
        this.tblEmpleado = tblEmpleado;
        this.documento = documento;
        this.fecha = fecha;
        this.total = total;
        this.confirmado = confirmado;
        this.fechaConfirmacion = fechaConfirmacion;
        this.anulado = anulado;
    }
    public TblCompraReferencia(long codigoCompraR, TblEmpleado tblEmpleado, String documento, Date fecha, BigDecimal total, boolean confirmado, String numeroEnvio, Date fechaConfirmacion, boolean anulado, Set tblCompraDetalles) {
       this.codigoCompraR = codigoCompraR;
       this.tblEmpleado = tblEmpleado;
       this.documento = documento;
       this.fecha = fecha;
       this.total = total;
       this.confirmado = confirmado;
       this.numeroEnvio = numeroEnvio;
       this.fechaConfirmacion = fechaConfirmacion;
       this.anulado = anulado;
       this.tblCompraDetalles = tblCompraDetalles;
    }
   
    public long getCodigoCompraR() {
        return this.codigoCompraR;
    }
    
    public void setCodigoCompraR(long codigoCompraR) {
        this.codigoCompraR = codigoCompraR;
    }
    public TblEmpleado getTblEmpleado() {
        return this.tblEmpleado;
    }
    
    public void setTblEmpleado(TblEmpleado tblEmpleado) {
        this.tblEmpleado = tblEmpleado;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public boolean isConfirmado() {
        return this.confirmado;
    }
    
    public void setConfirmado(boolean confirmado) {
        this.confirmado = confirmado;
    }
    public String getNumeroEnvio() {
        return this.numeroEnvio;
    }
    
    public void setNumeroEnvio(String numeroEnvio) {
        this.numeroEnvio = numeroEnvio;
    }
    public Date getFechaConfirmacion() {
        return this.fechaConfirmacion;
    }
    
    public void setFechaConfirmacion(Date fechaConfirmacion) {
        this.fechaConfirmacion = fechaConfirmacion;
    }
    public boolean isAnulado() {
        return this.anulado;
    }
    
    public void setAnulado(boolean anulado) {
        this.anulado = anulado;
    }
    public Set getTblCompraDetalles() {
        return this.tblCompraDetalles;
    }
    
    public void setTblCompraDetalles(Set tblCompraDetalles) {
        this.tblCompraDetalles = tblCompraDetalles;
    }




}


