package model;
// Generated Aug 29, 2017 11:31:30 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TblCompraDetalle generated by hbm2java
 */
public class TblCompraDetalle  implements java.io.Serializable {


     private long codigoCompraDetalle;
     private TblCompraReferencia tblCompraReferencia;
     private TblProducto tblProducto;
     private BigDecimal cantidad;
     private BigDecimal pcompra;

    public TblCompraDetalle() {
    }

    public TblCompraDetalle(long codigoCompraDetalle, TblCompraReferencia tblCompraReferencia, TblProducto tblProducto, BigDecimal cantidad, BigDecimal pcompra) {
       this.codigoCompraDetalle = codigoCompraDetalle;
       this.tblCompraReferencia = tblCompraReferencia;
       this.tblProducto = tblProducto;
       this.cantidad = cantidad;
       this.pcompra = pcompra;
    }
   
    public long getCodigoCompraDetalle() {
        return this.codigoCompraDetalle;
    }
    
    public void setCodigoCompraDetalle(long codigoCompraDetalle) {
        this.codigoCompraDetalle = codigoCompraDetalle;
    }
    public TblCompraReferencia getTblCompraReferencia() {
        return this.tblCompraReferencia;
    }
    
    public void setTblCompraReferencia(TblCompraReferencia tblCompraReferencia) {
        this.tblCompraReferencia = tblCompraReferencia;
    }
    public TblProducto getTblProducto() {
        return this.tblProducto;
    }
    
    public void setTblProducto(TblProducto tblProducto) {
        this.tblProducto = tblProducto;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPcompra() {
        return this.pcompra;
    }
    
    public void setPcompra(BigDecimal pcompra) {
        this.pcompra = pcompra;
    }




}


