package model;
// Generated Aug 29, 2017 11:31:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblEmpleado generated by hbm2java
 */
public class TblEmpleado  implements java.io.Serializable {


     private int codigoEmpleado;
     private TblPuesto tblPuesto;
     private String nombre;
     private String direccion;
     private String dpi;
     private String telefono;
     private String celular;
     private Date fechaIngreso;
     private String nombreUsuario;
     private String passwordd;
     private Boolean tipoUsuario;
     private boolean activo;
     private Set tblCompraReferencias = new HashSet(0);

    public TblEmpleado() {
    }

	
    public TblEmpleado(int codigoEmpleado, TblPuesto tblPuesto, String nombre, String direccion, String dpi, Date fechaIngreso, boolean activo) {
        this.codigoEmpleado = codigoEmpleado;
        this.tblPuesto = tblPuesto;
        this.nombre = nombre;
        this.direccion = direccion;
        this.dpi = dpi;
        this.fechaIngreso = fechaIngreso;
        this.activo = activo;
    }
    public TblEmpleado(int codigoEmpleado, TblPuesto tblPuesto, String nombre, String direccion, String dpi, String telefono, String celular, Date fechaIngreso, String nombreUsuario, String passwordd, Boolean tipoUsuario, boolean activo, Set tblCompraReferencias) {
       this.codigoEmpleado = codigoEmpleado;
       this.tblPuesto = tblPuesto;
       this.nombre = nombre;
       this.direccion = direccion;
       this.dpi = dpi;
       this.telefono = telefono;
       this.celular = celular;
       this.fechaIngreso = fechaIngreso;
       this.nombreUsuario = nombreUsuario;
       this.passwordd = passwordd;
       this.tipoUsuario = tipoUsuario;
       this.activo = activo;
       this.tblCompraReferencias = tblCompraReferencias;
    }
   
    public int getCodigoEmpleado() {
        return this.codigoEmpleado;
    }
    
    public void setCodigoEmpleado(int codigoEmpleado) {
        this.codigoEmpleado = codigoEmpleado;
    }
    public TblPuesto getTblPuesto() {
        return this.tblPuesto;
    }
    
    public void setTblPuesto(TblPuesto tblPuesto) {
        this.tblPuesto = tblPuesto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getDpi() {
        return this.dpi;
    }
    
    public void setDpi(String dpi) {
        this.dpi = dpi;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPasswordd() {
        return this.passwordd;
    }
    
    public void setPasswordd(String passwordd) {
        this.passwordd = passwordd;
    }
    public Boolean getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(Boolean tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getTblCompraReferencias() {
        return this.tblCompraReferencias;
    }
    
    public void setTblCompraReferencias(Set tblCompraReferencias) {
        this.tblCompraReferencias = tblCompraReferencias;
    }




}


