package model;
// Generated Aug 29, 2017 11:31:30 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblMovimiento generated by hbm2java
 */
public class TblMovimiento  implements java.io.Serializable {


     private long codigo;
     private TblProducto tblProducto;
     private String motivo;
     private double inicial;
     private Double entro;
     private Double salio;
     private double final_;
     private Date fecha;

    public TblMovimiento() {
    }

	
    public TblMovimiento(long codigo, TblProducto tblProducto, String motivo, double inicial, double final_, Date fecha) {
        this.codigo = codigo;
        this.tblProducto = tblProducto;
        this.motivo = motivo;
        this.inicial = inicial;
        this.final_ = final_;
        this.fecha = fecha;
    }
    public TblMovimiento(long codigo, TblProducto tblProducto, String motivo, double inicial, Double entro, Double salio, double final_, Date fecha) {
       this.codigo = codigo;
       this.tblProducto = tblProducto;
       this.motivo = motivo;
       this.inicial = inicial;
       this.entro = entro;
       this.salio = salio;
       this.final_ = final_;
       this.fecha = fecha;
    }
   
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }
    public TblProducto getTblProducto() {
        return this.tblProducto;
    }
    
    public void setTblProducto(TblProducto tblProducto) {
        this.tblProducto = tblProducto;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public double getInicial() {
        return this.inicial;
    }
    
    public void setInicial(double inicial) {
        this.inicial = inicial;
    }
    public Double getEntro() {
        return this.entro;
    }
    
    public void setEntro(Double entro) {
        this.entro = entro;
    }
    public Double getSalio() {
        return this.salio;
    }
    
    public void setSalio(Double salio) {
        this.salio = salio;
    }
    public double getFinal_() {
        return this.final_;
    }
    
    public void setFinal_(double final_) {
        this.final_ = final_;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


