package model;
// Generated Aug 29, 2017 11:31:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblMarca generated by hbm2java
 */
public class TblMarca  implements java.io.Serializable {


     private int codigoMarca;
     private String nombre;
     private boolean activo;
     private Set tblProductos = new HashSet(0);

    public TblMarca() {
    }

	
    public TblMarca(int codigoMarca, String nombre, boolean activo) {
        this.codigoMarca = codigoMarca;
        this.nombre = nombre;
        this.activo = activo;
    }
    public TblMarca(int codigoMarca, String nombre, boolean activo, Set tblProductos) {
       this.codigoMarca = codigoMarca;
       this.nombre = nombre;
       this.activo = activo;
       this.tblProductos = tblProductos;
    }
   
    public int getCodigoMarca() {
        return this.codigoMarca;
    }
    
    public void setCodigoMarca(int codigoMarca) {
        this.codigoMarca = codigoMarca;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getTblProductos() {
        return this.tblProductos;
    }
    
    public void setTblProductos(Set tblProductos) {
        this.tblProductos = tblProductos;
    }




}


