package model;
// Generated Aug 29, 2017 11:31:30 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblProducto generated by hbm2java
 */
public class TblProducto  implements java.io.Serializable {


     private long codigoProducto;
     private TblCategoria tblCategoria;
     private TblMarca tblMarca;
     private TblProveedor tblProveedor;
     private TblUbicacion tblUbicacion;
     private Serializable descripcion;
     private BigDecimal descuento;
     private BigDecimal precio;
     private BigDecimal existenciaMinima;
     private BigDecimal existenciaMaxima;
     private BigDecimal existencia;
     private Date fechaVencimiento;
     private byte[] foto;
     private boolean activo;
     private Set tblCompraDetalles = new HashSet(0);
     private Set tblMovimientos = new HashSet(0);

    public TblProducto() {
    }

	
    public TblProducto(long codigoProducto, TblCategoria tblCategoria, TblMarca tblMarca, TblProveedor tblProveedor, TblUbicacion tblUbicacion, Serializable descripcion, BigDecimal descuento, BigDecimal precio, BigDecimal existenciaMinima, BigDecimal existenciaMaxima, BigDecimal existencia, Date fechaVencimiento, boolean activo) {
        this.codigoProducto = codigoProducto;
        this.tblCategoria = tblCategoria;
        this.tblMarca = tblMarca;
        this.tblProveedor = tblProveedor;
        this.tblUbicacion = tblUbicacion;
        this.descripcion = descripcion;
        this.descuento = descuento;
        this.precio = precio;
        this.existenciaMinima = existenciaMinima;
        this.existenciaMaxima = existenciaMaxima;
        this.existencia = existencia;
        this.fechaVencimiento = fechaVencimiento;
        this.activo = activo;
    }
    public TblProducto(long codigoProducto, TblCategoria tblCategoria, TblMarca tblMarca, TblProveedor tblProveedor, TblUbicacion tblUbicacion, Serializable descripcion, BigDecimal descuento, BigDecimal precio, BigDecimal existenciaMinima, BigDecimal existenciaMaxima, BigDecimal existencia, Date fechaVencimiento, byte[] foto, boolean activo, Set tblCompraDetalles, Set tblMovimientos) {
       this.codigoProducto = codigoProducto;
       this.tblCategoria = tblCategoria;
       this.tblMarca = tblMarca;
       this.tblProveedor = tblProveedor;
       this.tblUbicacion = tblUbicacion;
       this.descripcion = descripcion;
       this.descuento = descuento;
       this.precio = precio;
       this.existenciaMinima = existenciaMinima;
       this.existenciaMaxima = existenciaMaxima;
       this.existencia = existencia;
       this.fechaVencimiento = fechaVencimiento;
       this.foto = foto;
       this.activo = activo;
       this.tblCompraDetalles = tblCompraDetalles;
       this.tblMovimientos = tblMovimientos;
    }
   
    public long getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(long codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public TblCategoria getTblCategoria() {
        return this.tblCategoria;
    }
    
    public void setTblCategoria(TblCategoria tblCategoria) {
        this.tblCategoria = tblCategoria;
    }
    public TblMarca getTblMarca() {
        return this.tblMarca;
    }
    
    public void setTblMarca(TblMarca tblMarca) {
        this.tblMarca = tblMarca;
    }
    public TblProveedor getTblProveedor() {
        return this.tblProveedor;
    }
    
    public void setTblProveedor(TblProveedor tblProveedor) {
        this.tblProveedor = tblProveedor;
    }
    public TblUbicacion getTblUbicacion() {
        return this.tblUbicacion;
    }
    
    public void setTblUbicacion(TblUbicacion tblUbicacion) {
        this.tblUbicacion = tblUbicacion;
    }
    public Serializable getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(Serializable descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getExistenciaMinima() {
        return this.existenciaMinima;
    }
    
    public void setExistenciaMinima(BigDecimal existenciaMinima) {
        this.existenciaMinima = existenciaMinima;
    }
    public BigDecimal getExistenciaMaxima() {
        return this.existenciaMaxima;
    }
    
    public void setExistenciaMaxima(BigDecimal existenciaMaxima) {
        this.existenciaMaxima = existenciaMaxima;
    }
    public BigDecimal getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(BigDecimal existencia) {
        this.existencia = existencia;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getTblCompraDetalles() {
        return this.tblCompraDetalles;
    }
    
    public void setTblCompraDetalles(Set tblCompraDetalles) {
        this.tblCompraDetalles = tblCompraDetalles;
    }
    public Set getTblMovimientos() {
        return this.tblMovimientos;
    }
    
    public void setTblMovimientos(Set tblMovimientos) {
        this.tblMovimientos = tblMovimientos;
    }




}


