package model;
// Generated Aug 29, 2017 11:31:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblUbicacion generated by hbm2java
 */
public class TblUbicacion  implements java.io.Serializable {


     private short codigoUbicacion;
     private String nombre;
     private boolean activo;
     private Set tblProductos = new HashSet(0);

    public TblUbicacion() {
    }

	
    public TblUbicacion(short codigoUbicacion, String nombre, boolean activo) {
        this.codigoUbicacion = codigoUbicacion;
        this.nombre = nombre;
        this.activo = activo;
    }
    public TblUbicacion(short codigoUbicacion, String nombre, boolean activo, Set tblProductos) {
       this.codigoUbicacion = codigoUbicacion;
       this.nombre = nombre;
       this.activo = activo;
       this.tblProductos = tblProductos;
    }
   
    public short getCodigoUbicacion() {
        return this.codigoUbicacion;
    }
    
    public void setCodigoUbicacion(short codigoUbicacion) {
        this.codigoUbicacion = codigoUbicacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getTblProductos() {
        return this.tblProductos;
    }
    
    public void setTblProductos(Set tblProductos) {
        this.tblProductos = tblProductos;
    }




}


